# Generated by Django 2.0.2 on 2018-03-07 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tugas1', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
